CREATE TYPE "tipo_usuario" AS ENUM (
  'comum',
  'admin'
);

CREATE TYPE "status" AS ENUM (
  'S',
  'N'
);

CREATE TABLE "usuarios" (
  "id_usuario" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100),
  "usuario" varchar(100) UNIQUE NOT NULL,
  "senha_hash" varchar(1000) NOT NULL,
  "tipo" tipo_usuario DEFAULT 'comum',
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "provedor" (
  "id_provedor" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "provedor" integer,
  "status" status,
  "client_id" varchar(500),
  "secret" varchar(500)
);

CREATE TABLE "fechaduras" (
  "id_fechadura" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_provedor" integer NOT NULL,
  "chave_dispositivo" varchar(500) NOT NULL
);

CREATE TABLE "salas" (
  "id_sala" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100) NOT NULL,
  "descricao" varchar(1000),
  "id_fechadura" integer NOT NULL
);

CREATE TABLE "reservas" (
  "id_reserva" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" integer NOT NULL,
  "id_sala" integer NOT NULL,
  "data_reserva_inicial" timestamp,
  "data_reserva_final" timestamp,
  "status" status
);

CREATE TABLE "senhas_temporarias" (
  "id_senha" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_reserva" integer NOT NULL,
  "codigo" varchar(100) NOT NULL,
  "status" status
);

ALTER TABLE "fechaduras" ADD CONSTRAINT "provedor_fechadura" FOREIGN KEY ("id_provedor") REFERENCES "provedor" ("id_provedor");

ALTER TABLE "salas" ADD CONSTRAINT "salas_fechaduras" FOREIGN KEY ("id_fechadura") REFERENCES "fechaduras" ("id_fechadura");

ALTER TABLE "reservas" ADD CONSTRAINT "resevas_usuario" FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id_usuario");

ALTER TABLE "reservas" ADD CONSTRAINT "reservas_salas" FOREIGN KEY ("id_sala") REFERENCES "salas" ("id_sala");

ALTER TABLE "senhas_temporarias" ADD CONSTRAINT "senhas_reservas" FOREIGN KEY ("id_reserva") REFERENCES "reservas" ("id_reserva");

-- Inserir usuário administrador padrão
-- senha = "admin123" (bcrypt hash)
INSERT INTO usuarios (nome, usuario, senha_hash, tipo)
VALUES (
    'Administrador',
    'ADMINISTRADOR',
    '$2b$10$J0sOoXVsZouO81z/nAvya.8Lky1z3FFPXNH7eiRAgAWhdCEawLEpm', -- hash de "admin123"
    'admin'
);
